name: dlna_dart
description: simple dlna client
version: 0.0.5
repository: https://github.com/suconghou/dlna-dart
homepage: https://github.com/suconghou/dlna-dart
publish_to: https://pub.dev
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies: 
  xml: ^5.3.1
